[package]
name = "bitcask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
walkdir = "2.3.2"
bytes = "1.3.0"
tempfile = "3.3.0"
thiserror = "1.0.38"
dashmap = "5.4.0"